version: '3.8'
services:
  cassandra:
    image: docker.io/bitnami/cassandra:latest
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      #      - CASSANDRA_USERNAME=user
      - CASSANDRA_PASSWORD=password
volumes:
  cassandra_data:
    driver: local