spring:
  application:
    name: datum
  cassandra:
    contact-points: ${CASSANDRA_HOST}
    local-datacenter: datacenter1
    port: 9042
    keyspace-name: releases
    password: ${CASSANDRA_USERNAME}
    username: ${CASSANDRA_PASSWORD}
server:
  shutdown: graceful
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /system